[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "nodejs_18"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-bcmath",
  "npm install",
  "npm run build"
]
